"""Initial schema with PostGIS tables

Revision ID: a7a29feb1538
Revises: 
Create Date: 2025-11-19 22:02:47.317441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 # type: ignore
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7a29feb1538'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_destinations_location', 'destinations', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_destinations_country'), 'destinations', ['country'], unique=False)
    op.create_index(op.f('ix_destinations_id'), 'destinations', ['id'], unique=False)
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget_range', sa.String(length=20), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('mobility_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('historical_ratings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_preferences', 'user_profiles', ['preferences'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('average_visit_duration', sa.Integer(), nullable=True),
    sa.Column('price_range', sa.String(length=20), nullable=True),
    sa.Column('price_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('popularity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('accessibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attraction_category_rating', 'attractions', ['category', 'rating'], unique=False)
    op.create_index('idx_attraction_location', 'attractions', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_attractions_location', 'attractions', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_attractions_category'), 'attractions', ['category'], unique=False)
    op.create_index(op.f('ix_attractions_destination_id'), 'attractions', ['destination_id'], unique=False)
    op.create_index(op.f('ix_attractions_id'), 'attractions', ['id'], unique=False)
    op.create_index(op.f('ix_attractions_name'), 'attractions', ['name'], unique=False)
    op.create_index(op.f('ix_attractions_subcategory'), 'attractions', ['subcategory'], unique=False)
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('route_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_distance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('optimization_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('algorithms_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_itinerary_status', 'itineraries', ['status'], unique=False)
    op.create_index('idx_itinerary_user_date', 'itineraries', ['user_profile_id', 'start_date'], unique=False)
    op.create_index(op.f('ix_itineraries_destination_id'), 'itineraries', ['destination_id'], unique=False)
    op.create_index(op.f('ix_itineraries_id'), 'itineraries', ['id'], unique=False)
    op.create_index(op.f('ix_itineraries_user_profile_id'), 'itineraries', ['user_profile_id'], unique=False)
    op.create_table('attraction_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_attraction_id', sa.Integer(), nullable=False),
    sa.Column('to_attraction_id', sa.Integer(), nullable=False),
    sa.Column('distance_meters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('travel_time_minutes', sa.Integer(), nullable=False),
    sa.Column('transport_mode', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('route_geometry', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('traffic_factor', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_attraction_id'], ['attractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_attraction_id'], ['attractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attraction_connections_route_geometry', 'attraction_connections', ['route_geometry'], unique=False, postgresql_using='gist')
    op.create_index('idx_connection_from_to', 'attraction_connections', ['from_attraction_id', 'to_attraction_id'], unique=False)
    op.create_index('idx_connection_transport', 'attraction_connections', ['transport_mode'], unique=False)
    op.create_index(op.f('ix_attraction_connections_from_attraction_id'), 'attraction_connections', ['from_attraction_id'], unique=False)
    op.create_index(op.f('ix_attraction_connections_id'), 'attraction_connections', ['id'], unique=False)
    op.create_index(op.f('ix_attraction_connections_to_attraction_id'), 'attraction_connections', ['to_attraction_id'], unique=False)
    op.create_table('attraction_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('visit_context', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['attraction_id'], ['attractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rating_attraction_date', 'attraction_ratings', ['attraction_id', 'visit_date'], unique=False)
    op.create_index('idx_rating_user_attraction', 'attraction_ratings', ['user_profile_id', 'attraction_id'], unique=False)
    op.create_index(op.f('ix_attraction_ratings_attraction_id'), 'attraction_ratings', ['attraction_id'], unique=False)
    op.create_index(op.f('ix_attraction_ratings_id'), 'attraction_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_attraction_ratings_user_profile_id'), 'attraction_ratings', ['user_profile_id'], unique=False)
    op.create_table('itinerary_attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.Column('visit_order', sa.Integer(), nullable=False),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visit_rating', sa.Integer(), nullable=True),
    sa.Column('visit_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attraction_id'], ['attractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_itinerary_attraction', 'itinerary_attractions', ['itinerary_id', 'attraction_id'], unique=True)
    op.create_index('idx_visit_order', 'itinerary_attractions', ['itinerary_id', 'visit_order'], unique=False)
    op.create_index(op.f('ix_itinerary_attractions_attraction_id'), 'itinerary_attractions', ['attraction_id'], unique=False)
    op.create_index(op.f('ix_itinerary_attractions_id'), 'itinerary_attractions', ['id'], unique=False)
    op.create_index(op.f('ix_itinerary_attractions_itinerary_id'), 'itinerary_attractions', ['itinerary_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('sentiment_score >= -1.0 AND sentiment_score <= 1.0', name='check_sentiment_range'),
    sa.ForeignKeyConstraint(['attraction_id'], ['attractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_attraction_source', 'reviews', ['attraction_id', 'source'], unique=False)
    op.create_index('idx_review_sentiment', 'reviews', ['sentiment_label'], unique=False)
    op.create_index(op.f('ix_reviews_attraction_id'), 'reviews', ['attraction_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_attraction_id'), table_name='reviews')
    op.drop_index('idx_review_sentiment', table_name='reviews')
    op.drop_index('idx_review_attraction_source', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_itinerary_attractions_itinerary_id'), table_name='itinerary_attractions')
    op.drop_index(op.f('ix_itinerary_attractions_id'), table_name='itinerary_attractions')
    op.drop_index(op.f('ix_itinerary_attractions_attraction_id'), table_name='itinerary_attractions')
    op.drop_index('idx_visit_order', table_name='itinerary_attractions')
    op.drop_index('idx_itinerary_attraction', table_name='itinerary_attractions')
    op.drop_table('itinerary_attractions')
    op.drop_index(op.f('ix_attraction_ratings_user_profile_id'), table_name='attraction_ratings')
    op.drop_index(op.f('ix_attraction_ratings_id'), table_name='attraction_ratings')
    op.drop_index(op.f('ix_attraction_ratings_attraction_id'), table_name='attraction_ratings')
    op.drop_index('idx_rating_user_attraction', table_name='attraction_ratings')
    op.drop_index('idx_rating_attraction_date', table_name='attraction_ratings')
    op.drop_table('attraction_ratings')
    op.drop_index(op.f('ix_attraction_connections_to_attraction_id'), table_name='attraction_connections')
    op.drop_index(op.f('ix_attraction_connections_id'), table_name='attraction_connections')
    op.drop_index(op.f('ix_attraction_connections_from_attraction_id'), table_name='attraction_connections')
    op.drop_index('idx_connection_transport', table_name='attraction_connections')
    op.drop_index('idx_connection_from_to', table_name='attraction_connections')
    op.drop_index('idx_attraction_connections_route_geometry', table_name='attraction_connections', postgresql_using='gist')
    op.drop_table('attraction_connections')
    op.drop_index(op.f('ix_itineraries_user_profile_id'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_id'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_destination_id'), table_name='itineraries')
    op.drop_index('idx_itinerary_user_date', table_name='itineraries')
    op.drop_index('idx_itinerary_status', table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index(op.f('ix_attractions_subcategory'), table_name='attractions')
    op.drop_index(op.f('ix_attractions_name'), table_name='attractions')
    op.drop_index(op.f('ix_attractions_id'), table_name='attractions')
    op.drop_index(op.f('ix_attractions_destination_id'), table_name='attractions')
    op.drop_index(op.f('ix_attractions_category'), table_name='attractions')
    op.drop_index('idx_attractions_location', table_name='attractions', postgresql_using='gist')
    op.drop_index('idx_attraction_location', table_name='attractions', postgresql_using='gist')
    op.drop_index('idx_attraction_category_rating', table_name='attractions')
    op.drop_table('attractions')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_index('idx_user_preferences', table_name='user_profiles', postgresql_using='gin')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_id'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_country'), table_name='destinations')
    op.drop_index('idx_destinations_location', table_name='destinations', postgresql_using='gist')
    op.drop_table('destinations')
    # ### end Alembic commands ###